// my-svelte-app/src/App.svelte
<script>
  import { APP_CONFIG } from './lib/config.js';
  import Header from './components/Header.svelte';
  import MainContent from './components/MainContent.svelte';

  function loadDarkMode() {
    if (typeof localStorage === 'undefined') return false;
    try {
      const s = localStorage.getItem('darkMode');
      return s ? JSON.parse(s) : false;
    } catch {
      return false;
    }
  }

  let currentPage = $state(APP_CONFIG.defaultPage);
  let isDarkMode = $state(loadDarkMode());

  $effect(() => {
    document.documentElement.classList.toggle('dark-mode', isDarkMode);
    try {
      localStorage.setItem('darkMode', JSON.stringify(isDarkMode));
    } catch {
      /* ignore */
    }
  });

  const year = new Date().getFullYear();
</script>

<div id="wrapper" class="fade-in" class:dark-mode={isDarkMode}>
  <div class="bg" aria-hidden="true"></div>
  <a href="#main" class="skip-to-main">Skip to main content</a>
  <Header bind:currentPage bind:isDarkMode />
  <MainContent {currentPage} {isDarkMode} />
  <div id="copyright">
    <ul>
      <li>&copy; {year} Justin Sowden</li>
    </ul>
  </div>
</div>

// my-react-app/src/App.js
import React, { useState, useEffect } from 'react';
import './App.css';
import Header from './Components/Header';
import MainContent from './Components/MainContent';
import ErrorBoundary from './Components/ErrorBoundary';
import { APP_CONFIG } from './config/constants';

function App() {
  const [currentPage, setCurrentPage] = useState(APP_CONFIG.defaultPage);
  const [isDarkMode, setIsDarkMode] = useState(() => {
    const saved = localStorage.getItem('darkMode');
    return saved ? JSON.parse(saved) : false;
  });

  useEffect(() => {
    localStorage.setItem('darkMode', JSON.stringify(isDarkMode));
    document.documentElement.classList.toggle('dark-mode', isDarkMode);
  }, [isDarkMode]);

  const toggleDarkMode = () => {
    setIsDarkMode(!isDarkMode);
  };

  return (
    <div id="wrapper" className={isDarkMode ? 'dark-mode' : ''}>
      <a
        href="#main"
        className="skip-to-main"
        onFocus={(e) => {
          e.target.style.left = '0';
        }}
        onBlur={(e) => {
          e.target.style.left = '-9999px';
        }}
      >
        Skip to main content
      </a>
      <ErrorBoundary>
        <Header
          currentPage={currentPage}
          setCurrentPage={setCurrentPage}
          isDarkMode={isDarkMode}
          toggleDarkMode={toggleDarkMode}
        />
        <MainContent
          currentPage={currentPage}
          setCurrentPage={setCurrentPage}
        />
      </ErrorBoundary>
      <footer id="copyright">
        <p>&copy; {new Date().getFullYear()} Justin Sowden</p>
      </footer>
    </div>
  );
}

export default App;
